name: Deploy to CloudPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 5.78.199.41
          username: hcantarranas
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/hdimpulsodigital-cantarranas/htdocs/cantarranas.hdimpulsodigital.com
            if [ ! -d ".git" ]; then
              git clone https://github.com/hermesdda2/hcantarranas2.git .
            else
              git pull origin main
            fi
            npm install --production
            pm2 restart hcantarranas || pm2 start npm --name "hcantarranas" -- start
            pm2 save
